apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: node-selector-deploy
  labels: 
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata: 
      labels:
        app: nginx-app
    spec: 
      nodeSelector:
        node-name: worker01
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80