apiVersion: apps/v1
kind: Deployment
metadata:
spec: 
  template:
    metadata:
    spec:
      toleration:  
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: NoSchdule