apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-pod
  labels:
    app: resource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels: 
        app: resource
    spec:
      containers:
      - name: resource-demo
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu","2","--vm", "1", "--vm-bytes","1G", "--vm-hang","1"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - echo "hello"
          failureThreshold: 2
          periodSeconds: 2