apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod1
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
