#formula - d = ceil[a * (c/t)]
#d - desired number of replicas, a = current and actual number of replicas, c = current value of metrics, t= target value
# ceil(2 pods* (90/70)] ==> ceil (2.57) => 3 pods
# same way calulate the memory ciel, which is having highr value, create those many pods 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: seh-hpa
spec:
  minReplicas: 1
  maximumRelicas: 5
  metrics:
  - resource:
      name: cpu
      target:
      #if avg cpu usage is more than 70%, create a new pod
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seh-deploy
