apiVersion: v1
kind: Service
metadata:
  name: python-django-service
spec:
  type: NodePort
  selector: 
    app: django
  ports:
  - port: 8080
    #target port is the port, where application is actually running
    targetPort: 8000
    nodePort: 30007