apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ "{\"auths\": {\"891377342072.dkr.ecr.us-east-1.amazonaws.com\": {\"username\": \"example-user\", \"password\": \"QVdTOmV5SndZWGxzYjJGa0lqb2lSV1I2U0ROcU4zbG5UMWRzYW5OT1VYUlRkRUZJUVRkWFVHNTBUR2hvUTFZMlRrTTRZVlJGYlZRdkwxQjFZVTVOYmxCTFJWVTBMMnRKVW05aVVURTBkVzAwYVZBeFlYQnNObVpOYmt0c2ExUmxZbk1yU1ZWNU5rOVhiWGxQS3paVE9FNHlSazEwT1ZWWE0wdDBjMGRDSzI5SFkxZDFTVUZHYkZWdWQzcDJWVTVyVVRrMk5UQkRNV3BUVUVWM1JUQnFZbmxzUVcxS2JEWTNTRE5IYTBaNGNqaDRRWGt6ZFVObmIyUmtOa3hhTXpKM1JVSnJLMkpFV2pjeVJ6QkdXSHBhVlVWeVEzaERNa3RwU2toUldDOURjbWhXTTFSNk5FNW5kVmgxV1hoUlRsTjJVVE5FZDJ0NldsQk5TRGx2YW1KSE0yOXVSSHBCWVRJclZVRkRTakZ5TWtNek5IRkhkV2xHV214SE4xaFBjMmxVWTFOclVsZFZZV3A2VVROck1rc3JWR2R3YUdsTk5VOHpjMmxJZFRCdmNsRlZaV1ZYTVRsb2VFaFBZMjV0YmpaQ1VGTjNkR05MU1c1dGIydG1NR0poVUVSRWJuUlBlWGgyU2xocWNGSldUV2xEUkdSWmNYY3lPR2hRUW1wNVEwWkNZM0pUSzFsU1FrUjNNbEJTWjFGUWVsbHllR3BaT0V4YU9GUjZNRzVFYUZSSldVaDFOekpPY1ZkNlprVk5WVFZHYVhNM2NGZEthblJJTWpaME9YTjFSRTUzYTJkSU5HMUJhSEpuWlROQmRFTkphVXRhVURBdlJIZEZTMkkxVEZoM2JUQkxNamd5VGlzelVEbFdLekpOTUhZNGFHZFBXVGh2YWtnMFVrVkNiMDVYYURsaU5WSnJTRlZYZURrNFZGTktUalZpWW1wQlJWVXJaRnBrZDJKUFpuQlBTbFZZU2pablNuWjZZWEJJUkZKcVNuazFUMHcyYjNKRmFtSmthMEV6UkVGSE1HNWFZbVp5V2k5a1oyMTROMk5MS3lzNVZXeFJOalpLVkRSRlVFeGtiVGhxSzNadVYyaG5RbFpHZVVKWmRHc3hiR3hIU21kalRXUnFaRGxtYVZNd00wRlpWRUp6VmxWeVRIcG9URmQxZWtzMldXTmFTMUJxTkRSQlZtdHRjMUZ6U1RreWMwcExhV3RPVjJSbVNsVjVZV3RpVGpKM04weEdXRFpvY2k5UE1HdFVSbWgzYWxSWVlVaHNlVVY2ZGpkemJqVkZWak5QVEhGRFZtdGxRUzlET0dabmRYUmxPVFoyWnpWdmJGVktkMjR6U1dSMGVYWkNVa0owY0dod2MyZFNVRVZPYUdOaUszUjZkbTFRYldaeGNrMTROaTlDTDNwVmJWVnhUakZ0V1haalprRlRiR2hJYzJ4WFJrSjFRMlEzVnk5bU5sSkVOV2d2YlhKU2F5dHpPV3RvVUZoYVYyVlBZamhLU0RsTGJ6Wk9TMDh6YTBob1Nrd3ZhRXN5WkZGT1dIZzViVVpoYWxOUlRGcGhNa0pOY2xCelEwdERaM0JRVmpkRFduRTBORGREWmxOMk5EWjBaMFpPYmxKTE9IQlJlbUk0Vld4U2JrVlZRMjF5U0ZWNU1XZFJaa3hOV0dOVGIyWnZURVJWWVhGSFkzWm9RbGNyU25sME5EUjBPVzlIZDNCbk1tOUZXV1ExV0RKbGRVODNiRFEwUlUxNlFVNUlkVmhSTVRNMVRIQlJXWEpJUzNoT01XbHZNSFpGUm5Wd2NIaERaQ3RZYzNSYVQxQk5RaXN2WjJnM1JWVkZSekJLSWl3aVpHRjBZV3RsZVNJNklrRlJSVUpCU0doM2JUQlpZVWxUU21WU2RFcHROVzR4UnpaMWNXVmxhMWgxYjFoWVVHVTFWVVpqWlRsU2NUZ3ZNVFIzUVVGQlNEUjNaa0ZaU2t0dldrbG9kbU5PUVZGalIyOUhPSGRpVVVsQ1FVUkNiMEpuYTNGb2EybEhPWGN3UWtKM1JYZElaMWxLV1VsYVNVRlhWVVJDUVVWMVRVSkZSVVJRT1VKNE9YRk5Ra3R6Tldab1ZWZEZVVWxDUlVsQk4zZFpla3RVVEdGUlF6WlBibWMyVEdWVmRVRmlOSEl3WkZWdlZVSjRaWE5CYjBWRlNYRlhhbFVyTnpSQ1FtSmxaMDE1TXk5SFYwTTBNMHROZGtOR1JYQmhXV1kwZDBoVFZIY3hVMnRCV1RROUlpd2lkbVZ5YzJsdmJpSTZJaklpTENKMGVYQmxJam9pUkVGVVFWOUxSVmtpTENKbGVIQnBjbUYwYVc5dUlqb3hOekUxTWpnek1ERTNmUT09\"}}}" | b64enc }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: 891377342072.dkr.ecr.us-east-1.amazonaws.com/python-django-app:latest
        ports: 
        - containerPort: 80
        livenessProbe: 
          tcpSocket:
            port: 8080
      imagePullSecrets:
      - name: image-pull-secret