apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: minaxijoshi/python-django-app:latest
        ports: 
        - containerPort: 8000
        livenessProbe: 
          tcpSocket:
            port: 8000
        env:
        - name: DB-PORT
          valueFrom: 
            configMapKeyRef:
              name: test-cm
              key: db-port
        - name: HOST 
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: host
        - name: DBNAME 
          valueFrom:
            configMapKeyRef: 
              name: test-cm
              key: host