apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
  labels:
    app: nginx-2
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      nodeSelector: 
        node: woker1
      containers:
      - name: nginx-container-2
        image: nginx:latest
        ports:
        - containerPort: 80