apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
  labels:
    app: seh-green
spec:
  selector:
    matchLabels:
      app: seh-green
  replicas: 2
  template:
    metadata:
      name: green-deploy-container
      labels: 
        app: seh-green
    spec:
      containers:
      - name: seh-green-app-container
        image: minaxijoshi/sehblinkingapp-green:1.0.0
        ports:
        - containerPort: 8000
--- 
apiVersion: v1 
kind: Service
metadata:
  name: seh-green-svc
  labels:
    app: seh-green
spec:
  selector:
    app: seh-green
  type: NodePort
  ports:
  - nodePort: 30002
    port: 8000
    protocol: TCP
    targetPort: 8000