apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
    app: blue-app
spec:
  selector:
    matchLabels:
      app: blue-app
  replicas: 2
  template:
    metadata:
      name: blue-deploy-container
      labels: 
        app: blue-app
    spec:
      containers:
      - name: seh-blue-app-container
        image: minaxijoshi/sehblinkingapp-blue:3.0.0
        ports:
        - containerPort: 8000
--- 
apiVersion: v1 
kind: Service
metadata:
  name: seh-blue-svc
spec:
  selector:
    app: seh-blue
  type: NodePort
  ports:
  - nodePort: 30001
    port: 8000
    protocol: TCP
    targetPort: 8000
