apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  lables:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      lables:
        app: django
    spec:
      containers:
      - name: django-container
        image: python-django-app:latest
        ports: 
        - containerPort: 80
        livenessProbe: 
          tcpSocket:
            port: 8080