apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seh-ingress
spec:
  rules:
  - host: "successeduhub.online"
    http:
      paths:
      - pathType: Prefix
        path: /blinkapp/blink
        backend:
          service:
            name: python-green-deployment
            port:
              number: 80

