apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  annotations:
spec: 
  ingressClassName: nginx
  rules:
  - host: "foo.bar.com"
    http: 
      paths:
      - pathType: Prefix
        path: "/bar"
        backend: 
          service:
            #name: python-django-service
            name: seh-webapp-svc
            port: 
              number: 80
